version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "/ch11112"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "/ch11112"

